#!/bin/sh

install -d /usr/local/share/perl5/Tuning
install Tuning/* /usr/local/share/perl5/Tuning

install -d /usr/local/share/tuning
cp -ar tools /usr/local/share/tuning

install -m 755 tuning /usr/sbin/
